name: 'build and deploy'
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write 

jobs:
  build:
    name: npm build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repos default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.x
          cache: npm
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::471585674330:role/github-actions-deploy
          aws-region: us-east-1
      - name: deploy cdk stack
        run: npx cdk deploy --all --require-approval never