name: 'build'
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Check all links
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.x
          cache: npm
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: npm run build
        run: echo 'HELLO GITHUB ACTIONS'